Data comes from https://users.nber.org/~rdehejia/data/.nswdata2.html

In [ ]:

import pandas as pd

In [13]:
columns = ["treatment", "age", "education", "black", "hispanic", "married", "nodegree", "RE75", "RE78"]

df_treated = pd.read_csv("nsw_treated.txt", delimiter="  ", names=columns)
df_control = pd.read_csv("nsw_control.txt", delimiter="  ", names=columns)

/tmp/ipykernel_666269/2014298986.py:3: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_treated = pd.read_csv("nsw_treated.txt", delimiter="  ", names=columns)
/tmp/ipykernel_666269/2014298986.py:4: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df_control = pd.read_csv("nsw_control.txt", delimiter="  ", names=columns)

In [15]:
df_merged = pd.concat([df_treated, df_control]).astype({
    "treatment": bool,
    "age": int,
    "education": int,
    "black": bool,
    "hispanic": bool,
    "married": bool,
    "nodegree": bool
})
df_merged

,treatment,age,education,black,hispanic,married,nodegree,RE75,RE78
0,True,37,11,True,False,True,True,0.0000,9930.0460
1,True,22,9,False,True,False,True,0.0000,3595.8940
2,True,30,12,True,False,False,False,0.0000,24909.4500
3,True,27,11,True,False,False,True,0.0000,7506.1460
4,True,33,8,True,False,False,True,0.0000,289.7899
...,...,...,...,...,...,...,...,...,...
420,False,20,10,True,False,False,True,825.2301,0.0000
421,False,17,9,False,True,False,True,0.0000,5114.8140
422,False,17,9,True,False,False,True,1206.4410,0.0000
423,False,19,11,True,False,False,True,0.0000,0.0000
424,False,18,10,True,False,False,True,0.0000,781.2243

In [18]:
df_merged.rename(columns={
    c: f"t:{c}" for c in ["treatment"]
}).rename(columns={
    c: f"c:{c}" for c in df_merged.columns if c not in ["treatment", "RE78"]
}).rename(columns={
    c: f"o:{c}" for c in ["RE78"]
}).to_csv("nsw.csv", index=False)

In [20]:
from causalitygame.generators.db_generator import DatabaseDrivenSCMGenerator

In [ ]:
gen = DatabaseDrivenSCMGenerator(
    factual_df=pd.read_csv("nsw.csv"),
    outcome_generator=lambda x: [0]
)